"""Interactive, cross-platform .env setup wizard."""

from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path


SECTION_PATTERN = re.compile(r"^##\s+(.+?)\s*$")
ENTRY_PATTERN = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
SECRET_SUFFIXES = ("_API_KEY", "_SECRET", "_PASSWORD", "_ACCESS_TOKEN")


@dataclass
class Section:
    name: str
    entries: list[tuple[str, str]] = field(default_factory=list)


def parse_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            pass
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1]
    return value


def read_values(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ENTRY_PATTERN.match(line.strip())
        if match:
            values[match.group(1)] = parse_value(match.group(2))
    return values


def read_template(path: Path) -> list[Section]:
    sections: list[Section] = []
    current: Section | None = None

    for line in path.read_text(encoding="utf-8").splitlines():
        section_match = SECTION_PATTERN.match(line)
        if section_match:
            current = Section(section_match.group(1))
            sections.append(current)
            continue

        entry_match = ENTRY_PATTERN.match(line.strip())
        if not entry_match:
            continue
        if current is None:
            current = Section("General")
            sections.append(current)
        current.entries.append((entry_match.group(1), parse_value(entry_match.group(2))))

    return [section for section in sections if section.entries]


def ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    while True:
        answer = input(prompt + suffix).strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("Please enter y or n.")


def ask_value(key: str, current: str | None, default: str) -> str | None:
    is_secret = key.endswith(SECRET_SUFFIXES)
    fallback = current if current is not None else default
    if current is not None and is_secret:
        hint = " [keep current]"
    elif fallback:
        hint = f" [{fallback}]"
    else:
        hint = ""

    prompt = f"  {key}{hint}: "
    value = getpass.getpass(prompt) if is_secret else input(prompt)
    if value == "-":
        return None
    return value if value else fallback


def serialize_value(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_env(path: Path, sections: list[Section], values: dict[str, str]) -> None:
    lines = ["# Generated by setup_env.py"]
    known_keys: set[str] = set()

    for section in sections:
        configured = [(key, values[key]) for key, _ in section.entries if key in values]
        known_keys.update(key for key, _ in section.entries)
        if not configured:
            continue
        lines.extend(["", f"# {section.name}"])
        lines.extend(f"{key}={serialize_value(value)}" for key, value in configured)

    extra = [(key, value) for key, value in values.items() if key not in known_keys]
    if extra:
        lines.extend(["", "# Existing custom variables"])
        lines.extend(f"{key}={serialize_value(value)}" for key, value in extra)

    content = "\n".join(lines) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)


def configure(template_path: Path, output_path: Path) -> None:
    sections = read_template(template_path)
    existing = read_values(output_path)
    values = dict(existing)

    print(f"Configure environment variables for {output_path.name}.")
    print("Press Enter to keep the shown value, or enter - to omit a variable.\n")

    for section in sections:
        keys = {key for key, _ in section.entries}
        has_existing = bool(keys & existing.keys())
        if not ask_yes_no(f"Configure {section.name}?", default=has_existing):
            continue
        for key, default in section.entries:
            value = ask_value(key, existing.get(key), default)
            if value is None:
                values.pop(key, None)
            else:
                values[key] = value

    write_env(output_path, sections, values)
    print(f"\nSaved {output_path}")


def main() -> None:
    project_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--template",
        type=Path,
        default=project_dir / ".env.example",
        help="environment template (default: .env.example)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_dir / ".env",
        help="file to create or update (default: .env)",
    )
    args = parser.parse_args()

    if not args.template.exists():
        parser.error(f"template not found: {args.template}")
    try:
        configure(args.template, args.output)
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled. No changes were saved.")


if __name__ == "__main__":
    main()
